Class {
	#name : #PMarker,
	#superclass : #Object,
	#instVars : [
		'node',
		'definition',
		'attribute'
	],
	#category : #'Painting-Editor'
}

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:48'
}
PMarker >> attribute [

	^ attribute
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:52'
}
PMarker >> attribute: aTextAttribute [

	attribute := aTextAttribute
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:47'
}
PMarker >> definition [

	^ definition
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:47'
}
PMarker >> definition: aDefinition [

	definition := aDefinition
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:47'
}
PMarker >> node [

	^ node
]

{
	#category : #'as yet unclassified',
	#'squeak_changestamp' : 'tobe 4/17/2024 11:47'
}
PMarker >> node: aNode [

	node := aNode
]
